pub const Instruction = enum(u8) {
    // Datatypes are only valid for constants
    NUMBER,
    STRING,
    CONSTANTS_DONE, // Marks end of constant definition
    CONSTANT,
    FUNCTION_START,
    FUNCTIONS_DONE, // Marks end of top-level function definitions
    CLOSURE_START,
    CLOSURE_END,
    UPVALUE_DEFINE,
    UPVALUE_DONE,
    TRUE,
    FALSE,
    NIL,
    NOT,
    NEGATE,
    EQUAL,
    NOT_EQUAL,
    LESS,
    LESS_EQUAL,
    GREATER,
    GREATER_EQUAL,
    ADD,
    SUB,
    MUL,
    DIV,
    GLOBAL_DEFINE,
    GLOBAL_GET,
    GLOBAL_SET,
    LOCAL_GET,
    LOCAL_SET,
    LOCAL_DEFINE,
    LOCAL_POP,
    UPVALUE_GET,
    UPVALUE_SET,
    POP,
    PRINT,
    JUMP,
    JUMP_IF_FALSE,
    JUMP_IF_TRUE,
    JUMP_BACK,
    CALL,
    RETURN,
};
